# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demoMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1026, 719)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(20, 442, 991, 251))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setObjectName("label_2")
        self.listWidget_confidence = QtWidgets.QListWidget(self.splitter)
        self.listWidget_confidence.setObjectName("listWidget_confidence")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 991, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_picPath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_picPath.setObjectName("lineEdit_picPath")
        self.gridLayout.addWidget(self.lineEdit_picPath, 0, 0, 1, 1)
        self.pushButton_selectPic = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_selectPic.setObjectName("pushButton_selectPic")
        self.gridLayout.addWidget(self.pushButton_selectPic, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.lineEdit__bias = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit__bias.sizePolicy().hasHeightForWidth())
        self.lineEdit__bias.setSizePolicy(sizePolicy)
        self.lineEdit__bias.setObjectName("lineEdit__bias")
        self.gridLayout.addWidget(self.lineEdit__bias, 0, 3, 1, 1)
        self.pushButton_gerResult = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_gerResult.setObjectName("pushButton_gerResult")
        self.gridLayout.addWidget(self.pushButton_gerResult, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_oriImg = QtWidgets.QLabel(self.groupBox_3)
        self.label_oriImg.setGeometry(QtCore.QRect(10, 20, 311, 351))
        self.label_oriImg.setText("")
        self.label_oriImg.setObjectName("label_oriImg")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setObjectName("groupBox")
        self.label_preImg = QtWidgets.QLabel(self.groupBox)
        self.label_preImg.setGeometry(QtCore.QRect(10, 20, 311, 351))
        self.label_preImg.setText("")
        self.label_preImg.setObjectName("label_preImg")
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_incateImg = QtWidgets.QLabel(self.groupBox_2)
        self.label_incateImg.setGeometry(QtCore.QRect(10, 20, 311, 351))
        self.label_incateImg.setText("")
        self.label_incateImg.setObjectName("label_incateImg")
        self.horizontalLayout.addWidget(self.groupBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "置信度列表"))
        self.pushButton_selectPic.setText(_translate("MainWindow", "选择图片"))
        self.label.setText(_translate("MainWindow", "阈值："))
        self.lineEdit__bias.setText(_translate("MainWindow", "0.1"))
        self.pushButton_gerResult.setText(_translate("MainWindow", "查看结果"))
        self.groupBox_3.setTitle(_translate("MainWindow", "原图"))
        self.groupBox.setTitle(_translate("MainWindow", "预测图片"))
        self.groupBox_2.setTitle(_translate("MainWindow", "正确标注图"))
